%%% Base algorithm

tic

[lambdas, L_ijkt, L_jkt, L_jt, wages, rentals, E_jkt, X_ikt, H_it, ...
    s_ikt, P_jt, welf_ijkt] = alg_lambdas(I, J, K, T, L_ik0, L_i0, ...
    Hbar_it, b_it, A_ikt, tau_ijkt, mu_ijkt, a_kt, sbar_k, beta, ...
    lambda_crit, lambda_tol, max_iter, w_crit, r_crit, wr_tol, zeta, ...
    gamma_k, kappa_pi, eta, sigma, v, kappa, phi, E_jkt, X_ikt, H_it, ...
    s_ikt, P_jt);

toc